config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'business', to: 'pages#business'
  get 'income', to: 'pages#income'
  get 'calendar', to: 'pages#calendar'
  resources :yachts do
    resources :bookings, only:[:new,:create]
  end
  resources :chatrooms, only: [:show,:index,:new,:create] do
    resources :messages, only: :create
  end
  get 'my_yachts', to: 'yachts#my_yachts'
  get 'your_crew', to: 'yachts#your_crew'
  patch 'yachts/:id/update_location', to: 'yachts#update_location'
  get 'tracker', to: 'yachts#tracker'
  get 'tracker_move', to: 'yachts#tracker_move'
  resources :bookings ,only: [:edit,:destroy,:update,:index]
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatrooms = Chatroom.all
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      redirect_to chatrooms_path
    else
      render :new
    end
  end
  private

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end

end

app/views/chatrooms/index.html.erb
<div class="wrapper">
<%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>CHATROOMS</h1>
    <%= link_to "Create Chatroom", new_chatroom_path, class: "lrg-blue-btn" %>
    <h6>Please select the channel you would like to join and start your conversation</h6>
    <table class="yachts-table">
      <thead>
        <tr>
          <th>Channels</th>
            <th></th>
        </tr>
      </thead>
      <tbody>
        <% @chatrooms.each do |chatroom| %>
          <tr>
            <td><%= chatroom.name %></td>
            <td><%= link_to "Enter", chatroom_path(chatroom), class: "lrg-blue-btn" %></td>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/chatrooms/new.html.erb
<%= simple_form_for(@chatroom) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/chatrooms/show.html.erb
<div class="wrapper">
<%= render "shared/side-bar" %>
  <div class="main_content">
  <h1>CHATROOM</h1>
    <div class="container chatroom" style= "height: 90%; margin-top:100px"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1>#<%= @chatroom.name %></h1>
  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <div id="message-<%= message.id %>">
        <small>
          <strong><%= message.user.username %></strong>
          <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
        </small>
        <p><%= message.content %></p>
      </div>
    <% end %>
  </div>

    <%= simple_form_for [@chatroom, @message],
      html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f|
    %>
        <%= f.input :content,
          label: false,
          placeholder: "Message ##{@chatroom.name}",
          wrapper_html: {class: "flex-grow-1"}
        %>
        <%= f.submit "Send", class: "lrg-blue-btn" %>
      <% end %>
    </div>

  </div>
</div>