config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'business', to: 'pages#business'
  get 'income', to: 'pages#income'
  get 'calendar', to: 'pages#calendar'
  resources :yachts do
    resources :bookings, only:[:new,:create]
  end
  resources :chatrooms, only: [:show,:index,:new,:create] do
    resources :messages, only: :create
  end
  get 'my_yachts', to: 'yachts#my_yachts'
  get 'your_crew', to: 'yachts#your_crew'
  patch 'yachts/:id/update_location', to: 'yachts#update_location'
  get 'tracker', to: 'yachts#tracker'
  get 'tracker_move', to: 'yachts#tracker_move'
  resources :bookings ,only: [:edit,:destroy,:update,:index]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :yacht
  has_one :income, dependent: :destroy

  def start_time
    self.check_in
  end

  def end_time
    self.check_out
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_yacht, only: [:new, :create]

  def index
    @bookings = Booking.all
    @incomes = Income.all
  end

  def new
    @booking = Booking.new

  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.yacht = @yacht




    if @booking.save!
      redirect_to bookings_path
      amount = @booking.yacht.price * (@booking.check_out - @booking.check_in).to_i
      Income.create(amount: amount, date: Date.today, booking: @booking, user: current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # authorize @booking
    @booking = Booking.find(params[:id])

  end


  def update
    # authorize @yacht
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to bookings_path, notice: 'Upadated successfully!', status: :see_other
    else
      render :edit
    end
  end

  def destroy
    # authorize @booking
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, notice: 'Booking was successfully destroyed!', status: :see_other
  end
  private

  def booking_params
    params.require(:booking).permit(:id,:check_in, :check_out,:total,:agency)
  end

  def set_yacht
    @yacht = Yacht.find(params[:yacht_id])
  end

end

app/views/bookings/edit.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <div class="row">
      <div class="col">
      <h1>EDIT EXISTING BOOKING</h1>
      <%= simple_form_for @booking do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" style="width: 1000px;">
      <label for="booking_check_in">Check-in date</label>
    <%= f.input :check_in, as: :date, html5: true, label: false %>

    <label for="booking_check_out">Check-out date</label>
    <%= f.input :check_out, as: :date, html5: true, label: false %>

    <%# <label for="booking_total">Total</label>
    <%= f.input :total, label: false %>

    <label for="booking_agency">Agency</label>
    <%= f.input :agency, label: false %>
  </div>


  <div class="form-actions">
    <%= f.button :submit, class: "lrg-blue-btn" , value: "Submit" %>
  </div>
<% end %>

      </div>
    </div>
  </div>

</div>

app/views/bookings/index.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>LIST OF BOOKINGS</h1>
    <table class="yachts-table">
      <thead>
        <tr>
          <th>Check in</th>
            <th>Check out</th>
            <th>Amount</th>
            <th>Location</th>
            <th>Agency</th>
            <th>Yacht name</th>
            <th></th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.check_in %></td>
            <td><%= booking.check_out %></td>
            <% if @incomes.find_by(booking_id: booking.id).present? %>
              <td><%= @incomes.find_by(booking_id: booking.id).amount %></td>
            <% else %>
              <td> - </td>
            <% end %>
            <td><%= booking.yacht.location %></td>
            <td><%= booking.agency %></td>
            <td><%= booking.yacht.name %></td>
            <td>
              <%= link_to "Edit", edit_booking_path(booking), class: "lrg-blue-btn" %>
              <%= link_to "Delete",booking_path(booking),data: {turbo_method: "delete"}, class: "lrg-blue-btn" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <div class="row">
      <div class="col">
      <h1>RESERVE YOUR YACHT</h1>
      <%= simple_form_for [@yacht, @booking], data: { controller: 'flatpickr' } do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs" style="width: 1000px;">
               <%= f.input :check_in, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
                <%= f.input :check_out, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>

            <label for="booking_agency" style="margin-bottom: 10px;">Agency</label>
            <%= f.input :agency, label: false, placeholder: "Name of the booking agency" %>
          </div>


            <div class="form-actions">
              <%= f.button :submit, class: "lrg-blue-btn" , value: "Book now!" %>
            </div>
          <% end %>
    </div>
  </div>
</div>