config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'business', to: 'pages#business'
  get 'income', to: 'pages#income'
  get 'calendar', to: 'pages#calendar'
  resources :yachts do
    resources :bookings, only:[:new,:create]
  end
  resources :chatrooms, only: [:show,:index,:new,:create] do
    resources :messages, only: :create
  end
  get 'my_yachts', to: 'yachts#my_yachts'
  get 'your_crew', to: 'yachts#your_crew'
  patch 'yachts/:id/update_location', to: 'yachts#update_location'
  get 'tracker', to: 'yachts#tracker'
  get 'tracker_move', to: 'yachts#tracker_move'
  resources :bookings ,only: [:edit,:destroy,:update,:index]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "YMS-logo.png" %>
    <% end %>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <span class="navbar-text text-dark" style="margin-right: 15px;">
            <%= current_user.email %>
          </span>

          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.key %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", crop: :fill %>
            <% else %>
              <%= image_tag "avatar.jpeg", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Your crew", your_crew_path, class: "dropdown-item" %>
              <%= link_to "Yours yachts", my_yachts_path, class: "dropdown-item" %>
              <%= link_to "Edit your profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>

        <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Actions
        </button>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
          <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
        </div>
      </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_side-bar.html.erb
<div class="sidebar">
  <ul>
  <li>
    <div class="nav-block">
      <div class="icon">
        <i class="fas fa-calendar"></i>
      </div>
      <div class="link">
        <%= link_to "Calendar", calendar_path %>
      </div>
    </div>
  </li>
  <li>
    <div class="nav-block">
      <div class="icon">
        <i class="fas fa-check"></i>
      </div>
      <div class="link">
        <%= link_to "Bookings", bookings_path %>
      </div>
    </div>
  </li>
  <li>
    <div class="nav-block">
      <div class="icon">
        <i class="fas fa-sailboat"></i>
      </div>
      <div class="link">
        <%= link_to "Yachts", yachts_path %>
      </div>
    </div>
  </li>
  <li>
     <div class="nav-block">
      <div class="icon">
        <i class="fa-solid fa-business-time"></i>
      </div>
      <div class="link">
        <%= link_to "Business", business_path %>
      </div>
    </div>
  </li>
  <li>
    <div class="nav-block">
      <div class="icon">
        <i class="fa-solid fa-sack-dollar"></i>
      </div>
      <div class="link">
        <%= link_to "Income", income_path %>
      </div>
    </div>
  </li>
  <li>
    <div class="nav-block">
      <div class="icon">
        <i class="fas fa-map"></i>
      </div>
      <div class="link">
        <%= link_to "Tracker", tracker_path %>
      </div>
    </div>
  </li>
  <li>
    <div class="nav-block">
      <div class="icon">
        <i class="fa-solid fa-comments"></i>
      </div>
      <div class="link">
        <%= link_to "Chatroom", chatrooms_path %>
      </div>
    </div>
  </li>
  </ul>
</div>