config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'business', to: 'pages#business'
  get 'income', to: 'pages#income'
  get 'calendar', to: 'pages#calendar'
  resources :yachts do
    resources :bookings, only:[:new,:create]
  end
  resources :chatrooms, only: [:show,:index,:new,:create] do
    resources :messages, only: :create
  end
  get 'my_yachts', to: 'yachts#my_yachts'
  get 'your_crew', to: 'yachts#your_crew'
  patch 'yachts/:id/update_location', to: 'yachts#update_location'
  get 'tracker', to: 'yachts#tracker'
  get 'tracker_move', to: 'yachts#tracker_move'
  resources :bookings ,only: [:edit,:destroy,:update,:index]
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  geocoded_by :location
  after_validation :geocode_if_location_changed_and_not_offshore
  belongs_to :user
  validates :name, presence: true

  private

  def geocode_if_location_changed_and_not_offshore
    if will_save_change_to_location? && location != 'Offshore'
      geocode
    end
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_yacht, only: [:edit, :update, :destroy, :show]
  before_action :map_yacht, only: [:tracker, :tracker_move]

  def index
    if current_user.crew.present?
      @yachts = Yacht.joins(:user).where(users: { crew: current_user.crew })
    else
      @yachts = Yacht.where(user: current_user)
    end
  end

  def tracker
  end

  def tracker_move
  end

  def new
    @yacht = Yacht.new
  end

  def create
    @yacht = Yacht.new(yacht_params)
    @yacht.user = current_user
    if @yacht.save
      redirect_to yachts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update_location
    yacht = Yacht.find(params[:id])
    latitude = location_params[:latitude]
    longitude = location_params[:longitude]
    yacht.update(location_params)
    location_result = Geocoder.search([latitude, longitude]).first

    if location_result && location_result.city.present?
      render json: { message: location_result.city}
      yacht.update(location: location_result.city)
      #redirect_to tracker_move_path
    else
      render json: { message: "Unable to determine city from coordinates."}
      yacht.update(location: "Offshore")
    end
  end

  def update
    @yacht.user = current_user
    if @yacht.update(yacht_params)
      redirect_to yacht_path(@yacht), notice: 'Upadated successfully!', status: :see_other
    else
      render :edit
    end
  end

  def my_yachts
    @yachts = Yacht.where(user: current_user)
    render :index
  end

  def destroy
    @yacht.destroy
    redirect_to yachts_path, notice: 'Yacht was successfully destroyed!', status: :see_other
  end

  def show
  end


  def your_crew
    @users = User.all
  end

  private

  def location_params
    params.require(:yacht).permit(:latitude, :longitude)
  end

  def yacht_params
    params.require(:yacht).permit(:id,:name, :number_of_guests, :price, :location)
  end

  def set_yacht
    @yacht = Yacht.find(params[:id])
  end

  def map_yacht
    @yachts = Yacht.where(user: current_user)

    @markers = @yachts.geocoded.map do |yacht|
      {
        lat: yacht.latitude,
        lng: yacht.longitude,
        location: yacht.location,
        id: yacht.id,
        info_window_html: render_to_string(partial: "info_window", locals: {yacht: yacht}),
        marker_html: render_to_string(partial: "markers", locals: {yacht: yacht}),
        marker_html2: render_to_string(partial: "markers2", locals: {yacht: yacht})
      }
    end
  end
end

app/views/yachts/_form.html.erb
<%= simple_form_for(@yacht) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs" style="width: 1000px;">
    <%= f.input :name, placeholder: "Enter yacht name" %>
    <%= f.input :number_of_guests, placeholder: "Enter max boat capacity" %>
    <%= f.input :price, placeholder: "Price per day" %>
    <%= f.input :location, placeholder: "Town/city" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "" %>
  </div>
<% end %>

app/views/yachts/_info_window.html.erb
<h2> <%= link_to yacht.name, yacht_path(yacht.id) %></h2>
<p><%= yacht.location %></p>

app/views/yachts/_markers.html.erb
<div style="position: relative;">
  <% if yacht.location == "Offshore" %>
    <i class="fa-solid fa-ship" style="color: grey;"></i>
    <div class="badge rounded-pill bg-secondary fs-6" style="position: absolute; top: -30px; left: 50%; transform: translateX(-50%);">
  <% else %>
    <i class="fa-solid fa-ship" style="color: #111972;"></i>
    <div class="badge rounded-pill bg-primary fs-6" style="position: absolute; top: -30px; left: 50%; transform: translateX(-50%);">
  <% end %>
    <%= yacht.location %>
  </div>
</div>

app/views/yachts/_markers2.html.erb
<div style="position: relative;">
  <% if yacht.location == "Offshore" %>
    <i class="fa-solid fa-ship fa-flip" style="color: grey;"></i>
    <div class="badge rounded-pill bg-secondary fs-6" style="position: absolute; top: -30px; left: 50%; transform: translateX(-50%);">
  <% else %>
    <i class="fa-solid fa-ship fa-flip" style="color: #111972;"></i>
    <div class="badge rounded-pill bg-primary fs-6" style="position: absolute; top: -30px; left: 50%; transform: translateX(-50%);">
  <% end %>
    <%= yacht.location %>
  </div>
</div>

app/views/yachts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>EDIT YOUR YACHT</h1>
      <%= render "form", yacht: @yachts_path %>
    </div>
  </div>
</div>

app/views/yachts/index.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>LIST OF YACHTS</h1>
    <div class="button-container">
        <%= link_to "Filter My Yachts", my_yachts_path, class: "lrg-blue-btn" %>
        <%= link_to "All Yachts", yachts_path, class: "lrg-blue-btn" %>
        <%= link_to "Create a new yacht", new_yacht_path, class: "lrg-blue-btn" %>
    </div>

        <table class="yachts-table">
          <thead>
            <tr>
               <th class="sortable" data-sort-direction="asc">
                Name
              </th>
              <th>No. of people</th>
              <th>Daily rate($)</th>
              <th>Location</th>
              <th>Owner</th>
              <th>Email</th>
              <th>      </th>
            </tr>
          </thead>
          <tbody>
            <% @yachts.each do |yacht| %>
              <tr>
                <td><%= link_to yacht.name, yacht_path(yacht) %></td>
                <td><%= yacht.number_of_guests %></td>
                <td><%= yacht.price %></td>
                <td><%= yacht.location %></td>
                <td><%= yacht.user.username %></td>
                <td><%= yacht.user.email %></td>
                <% if yacht.user.id == current_user.id %>
                  <td><%= link_to "BOOK", new_yacht_booking_path(yacht), class: "lrg-blue-btn"%></td>
                <% else %>
                  <td> </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>

  </div>
</div>

app/views/yachts/new.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <div class="row">
      <div class="col">
        <h1>ADD NEW YACHT</h1>
      <%= render "form", yacht: @yachts_path %>
      </div>
    </div>

  </div>
</div>

app/views/yachts/show.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>YACHT DETAILS</h1>
    <div class="yacht-card">
      <h2><%= @yacht.name %></h2>
        <p><strong>Number of Guests:</strong> <%= @yacht.number_of_guests %></p>
        <p><strong>Price:</strong> <%= @yacht.price %>€</p>
        <p><strong>Location:</strong> <%= @yacht.location %></p>
        <p><strong>Owner:</strong> <%= @yacht.user.username %></p>
    </div>



    <div class="button-container">
        <%= link_to "Back to Yachts", yachts_path, class: "lrg-blue-btn" %>
        <%= link_to "Edit", edit_yacht_path(@yacht), class: "lrg-blue-btn" %>
        <%= button_to "Delete", @flat, class: "lrg-blue-btn", method: :delete%>
    </div>

  </div>
</div>

app/views/yachts/tracker.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>TRACKER</h1>
    <%= link_to "Move Your Yachts", tracker_move_path, class: "lrg-blue-btn mb-3" %>
    <div style="width: 80%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>

  </div>
</div>

app/views/yachts/tracker_move.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>MOVE YOUR YACHTS</h1>
    <div class="row d-flex justify-content-between">
      <div class="col-6">
        <%= link_to "Go back", tracker_path, class: "lrg-blue-btn mb-3" %>
      </div>
      <div class="col-6">
        <%= link_to "Refresh", tracker_move_path, class: "lrg-blue-btn mb-3" %>
      </div>
    </div>
    <div style="width: 80%; height: 600px;"
      data-controller="mapmove"
      data-mapmove-markers-value="<%= @markers.to_json %>"
      data-mapmove-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    >
    </div>


  </div>
</div>

app/views/yachts/your_crew.html.erb
<div class="wrapper">
  <%= render "shared/side-bar" %>
  <div class="main_content">
    <h1>Your crew</h1>
    <h2>The <%= current_user.crew %></h2>
    <div class="crew-flex">
      <% @users.each do |user| %>
        <% if  user.crew == current_user.crew %>
          <% if user.photo.key %>
              <div class="card-crew" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
          url('<%= cl_image_path user.photo.key, height: 300, width: 400, crop: :fill %>')">
          <% else %>
            <div class="card-crew" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
        url('<%= image_path "avatar.jpeg", height: 300, width: 400, crop: :fill %>')">
          <% end %>


            <h4><%= user.username.capitalize %></h4>
          </div>


          <%# <%= cl_image_tag user.photo.key, height: 300, width: 400, crop: :fill %>
          <%# <h4><%= user.username.capitalize %>
          <%# <p><%= user.email %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>